### ISSUE TITLE
Poor blade formatting/support 

### ISSUE THREAD

**Issue by oxio2** [kauffinger/lazyvim#2] opened 2023-08-04 16:29 UTC
Greetings,
I've been looking for days for a configuration that works with "blade.php" files, however even the most obscure solutions don't seem to work.
The repository description says that the config supports blade files, however html snippets don't work, php neither, neither tailwind.
Is this a general problem with blade files not being supported by the community, a config problem, or something wrong with my pc?

**Comment by oxio2** [comment] 2023-08-05 15:37
Greetings, these are all the information that you asked me for, all programs are in the most recent stable version.
All highligths, snippets, etc work on php only files, such as routes, models.... 
On blade files tho php, html, blade directives and tailwing classes don't 

This is a screenshot of lazyvim mason window, is it correct?
https://imgur.com/gallery/vxKeh5T

```
> php --version
PHP 8.2.8 (cli) (built: Jul 16 2023 11:01:56) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies
> nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
> php artisan --version
Laravel Framework 10.17.1
```

**Comment by kauffinger** [comment] 2023-08-05 15:41
Well that's interesting. Can you also run the `:checkhealth` command?

Did you copy some of my settings or are you using my config as a base?

**Comment by oxio2** [comment] 2023-08-05 15:56
I installed the repository settings alone, i did not change anything.

Checkhealth log
https://pastebin.com/0ELArMM0

lsp warn log
https://pastebin.com/4Ekw5vG7

**Comment by kauffinger** [comment] 2023-08-05 16:37
Well from checkhealth it seems everything should work. The issue seems that the files cannot be written. I have to be honest and tell you that I don't have a concrete idea what the issue is.

Looking at the message:
`[WARN][2023-08-04 15:37:40] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/example-app/resources/views/welcome.blade.php"`
My first (uneducated) guess would be file permissions, any chance that might be it?

**Comment by oxio2** [comment] 2023-08-05 18:41
that warn was indeed because of a permission issue, however after fixing it another issue occures

```
[START][2023-08-05 20:26:32] LSP logging initiated
[WARN][2023-08-05 20:26:32] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-08-05 20:26:33] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:26:33] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."
[WARN][2023-08-05 20:26:33] ...lsp/handlers.lua:537	"file:///home/oxio2/progamer/laravel/example-app/vendor/fakerphp/faker/src/Faker/Provider/nl_BE/Text.php is over the maximum file size of 1000000 bytes."
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[WARN][2023-08-05 20:29:21] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 13): "
[START][2023-08-05 20:30:55] LSP logging initiated
[WARN][2023-08-05 20:30:55] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2023-08-05 20:31:12] LSP logging initiated
[WARN][2023-08-05 20:31:12] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-08-05 20:31:12] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."
[WARN][2023-08-05 20:31:12] ...lsp/handlers.lua:537	"file:///home/oxio2/progamer/laravel/example-app/vendor/fakerphp/faker/src/Faker/Provider/nl_BE/Text.php is over the maximum file size of 1000000 bytes."
[WARN][2023-08-05 20:31:15] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:31:15] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[ERROR][2023-08-05 20:31:19] .../vim/lsp/rpc.lua:734	"rpc"	"node"	"stderr"	"[ERROR] [auth] [2023-08-05T18:31:19.277Z] Failed to send notification result to GitHub: 403 \n"
[WARN][2023-08-05 20:31:20] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:31:20] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:31:21] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:31:22] ...lsp/handlers.lua:537	"Failed to apply changes to file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php"
[WARN][2023-08-05 20:31:29] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 14): "
[WARN][2023-08-05 20:31:29] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 14): "
[WARN][2023-08-05 20:31:29] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 14): "
[WARN][2023-08-05 20:31:29] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 14): "
[WARN][2023-08-05 20:31:29] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 14): "
[START][2023-08-05 20:33:06] LSP logging initiated
[WARN][2023-08-05 20:33:06] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-08-05 20:33:06] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."
[WARN][2023-08-05 20:33:06] ...lsp/handlers.lua:537	"file:///home/oxio2/progamer/laravel/example-app/vendor/fakerphp/faker/src/Faker/Provider/nl_BE/Text.php is over the maximum file size of 1000000 bytes."
[START][2023-08-05 20:33:38] LSP logging initiated
[WARN][2023-08-05 20:33:38] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-08-05 20:33:39] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."
[WARN][2023-08-05 20:33:39] ...lsp/handlers.lua:537	"file:///home/oxio2/progamer/laravel/example-app/vendor/fakerphp/faker/src/Faker/Provider/nl_BE/Text.php is over the maximum file size of 1000000 bytes."
[WARN][2023-08-05 20:34:31] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 12): "
[WARN][2023-08-05 20:34:31] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 12): "
[WARN][2023-08-05 20:34:31] .../lua/vim/lsp.lua:1637	"buf_attach_client called on unloaded buffer (id: 12): "
[START][2023-08-05 20:35:17] LSP logging initiated
[WARN][2023-08-05 20:35:17] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-08-05 20:35:18] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."
[WARN][2023-08-05 20:35:18] ...lsp/handlers.lua:537	"file:///home/oxio2/progamer/laravel/example-app/vendor/fakerphp/faker/src/Faker/Provider/nl_BE/Text.php is over the maximum file size of 1000000 bytes."

```


The important warn seems to be
`[WARN][2023-08-05 20:35:18] ...lsp/handlers.lua:537	"textDocument/didOpen ignored. file:///home/oxio2/progamer/laravel/example-app/resources/views/welcome.blade.php has unsupported language ID blade."`

there seem to be missing a plugin that takes care of blade identified files?

**Comment by kauffinger** [comment] 2023-08-05 20:28
Hmmm I do know that by default, blade is not supported. But: I do have included a plugin that should fix that, see [here](https://github.com/kauffinger/lazyvim/blob/main/lua/plugins/extra_languages.lua).

When you execute `:echo &filetype`, do you get `blade` as the output?

**Comment by oxio2** [comment] 2023-08-06 12:21
the `vim-blade` plugin is installed and the `:echo $filetype` returns `blade` as the output

https://imgur.com/a/A82d2Ax

**Comment by kauffinger** [comment] 2023-08-07 07:24
Well that's really weird then. As the LSP plugin I/LazyVim use (null-ls), which this problem seems to stem from, is [archived in four days](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621#issue-1795450982) and I couldn't find any lead by googling the error message, I'll have to fold here.

I think I will wait for what new LSP plugin LazyVim adopts and then transfer the config to that. I know that that surely is not a satisfying answer for you, but I cannot replicate the problem locally and thus have no chance of efficiently debugging this. At the moment I am strapped for time, so if i come back around to it, I'll try to debug further - but that timeframe is probably a few months in the future and at that point I expect null-ls to be already replaced.

Thanks for bringing the problem to my attention and your cooperation in trying to debug! If you find the issue yourself, I'd love to hear the solution :)

**Comment by oxio2** [comment] 2023-08-09 17:16
Thank you very much for all the help, i will stay updated on the issue :)

**Comment by kauffinger** [comment] 2023-10-01 17:35
@oxio2 try with the new version now, null-ls is replaced by a fork called none-ls. Check [this](https://github.com/kauffinger/lazyvim/commit/a068080908ec4ee0fe5adc0c71cffbeec93d6f34#diff-a6b503a3808b7d105c68e91e8180c1b5b5524c2996a9227c71732c2632465074) commit for what to do to migrate.

Maybe it works now!

**Comment by kauffinger** [comment] 2023-10-18 09:59
Another bump, @oxio2 ! Formatting is now running via conform, good chance it all works now! Check out my migration branch. I'll close this when I merge the branch.

**Comment by kauffinger** [comment] 2023-10-23 16:28
Formatting now runs over conform.nvim, closing this.

**Closed by kauffinger** 2023-10-23 16:28 UTC
Labels: help wanted
